### ISSUE TITLE
running on windows

### ISSUE THREAD

**Issue by yaskshelat** [andrestumpf/coregis_public#1]
Can we run this on windows?
I tried to install this in windows conda, all libraries install ok, however I am not sure how to fill in parameter values

What is otbpath, micmac path below?
Also what is master granule and slave granule.?
Inside "GRANULE" folder, we have only  one subfolder "L1C_T08UPF_A012280_20171028T200735" (see snapshot below).  As given in the example.py script for master granule,There is no folder starting with "/S2A_MSIL1C......" Not sure what exactly is referred here?

![image](https://user-images.githubusercontent.com/36253068/37923083-442a3d2e-30fc-11e8-9d69-b1c36f38bfb3.png)

I will keep all other parameters as default as given in example.py script.

# set paths
fmask_path = os.path.dirname(sys.executable)
#otbpath = os.path.expanduser('/usr/bin')
#micmac_path = os.path.expanduser('~/micmac')
work_folder = os.path.expanduser(r'C:\WORK_FILES\test')

# set parameters for mask generation
pixel_size_x_cloud_mask = 30
pixel_size_y_cloud_mask = 30

# set parameters for matching
SzW=4
CorrelMin=0.3
Inc=2
RegulBase=0.2
mode='coregis'

# set parameters for corrections
iterations=3
zoom=0.25
cc_thresh=0.33

# set the input folders
master_granule = os.path.expanduser('~/Documents/test_data/S2A_OPER_PRD_MSIL1C_PDMC_20160128T013226_R092_V20160125T080606_20160125T080606.SAFE/GRANULE/S2A_OPER_MSI_L1C_TL_SGS__20160125T113126_A003092_T37PEL_N02.01')
slave_granule = os.path.expanduser('~/Documents/test_data/S2A_MSIL1C_20170119T074231_N0204_R092_T37PEL_20170119T075325.SAFE/GRANULE/L1C_T37PEL_A008240_20170119T075325')

Please guide
Yask

**Comment by andrestumpf** [comment]
Hi Yask,
...unfortunately we never tried to adapt this prototype for running on Windows and it probably won't happen. If you don't have access to a computer with a Linux distribution I'd recommend to go for a Virtual Machine using Ubuntu 16.04 on it.
Best,
André
